language: csharp
os: linux
mono: none
dotnet: 3.1
dist: xenial
script:
  - dotnet restore
  - dotnet build
  - dotnet test
after_script:
  - bash coverage ./TravisTest.Tests/bin/Debug/netcoreapp3.1/TravisTest.Tests.dll
  - bash <(curl -s https://codecov.io/bash)
