language: csharp
dist: xenial
dotnet: 3.1
os: linux
before_install:
  - wget --no-check-certificate https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
install:
  - mono ./nuget.exe install NUnit.Runners -Version 3.0.1 -OutputDirectory testrunner
script:
  - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
after_script:
  - dotnet coverage
  - bash <(curl -s https://codecov.io/bash)