language: csharp
os: linux
mono: none
dotnet: 3.1
dist: xenial
script:
  - dotnet restore
  - dotnet build
  - make compile test
after_script:
  - make coverage
  - bash <(curl -s https://codecov.io/bash)
