language: csharp
mono: none
dotnet: 3.1
script:
 - dotnet restore
 - dotnet build

curl -Os https://uploader.codecov.io/latest/linux/codecov

chmod +x codecov
./codecov -t ${62ece7e0-0235-4543-9ec6-3277e5931647}