language: csharp
mono: none
dotnet: 3.1
sudo: required
script:
  - dotnet restore
  - dotnet build
dotnet tool install -g Codecov.Tool --add-source "https://ci.appveyor.com/nuget/codecov-exe" --version "1.10.0-unstable0001"
